name: Mono Repo CI

on:  
  workflow_call:
    inputs:
      node:
        required: true
        type: string

jobs:
  ci:
    uses: duc168/workflows/.github/workflows/mono_repo_detect_changes_in_apps_v1.yml@master
    with:
      workflow_url: duc168/workflows/.github/workflows/pnpm_mono_repo_ci_each_app_v1.yml@master
      node: ${{ matrix.node }}
